-- AlterTable
ALTER TABLE "Image" ADD COLUMN     "url" TEXT,
ALTER COLUMN "data" DROP NOT NULL,
ALTER COLUMN "size" SET DEFAULT 0,
ALTER COLUMN "width" SET DEFAULT 0,
ALTER COLUMN "height" SET DEFAULT 0,
ALTER COLUMN "checksum" SET DEFAULT '';
